// <auto-generated />
using System;
using GestionIngresosHonorarios.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionIngresosHonorarios.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionIngresosHonorarios.Application.Contracts.AnnualRetentionRate", b =>
                {
                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("porcentaje");

                    b.HasKey("Year");

                    b.ToTable("retencion_boleta_honorarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_retencion_boleta_anio", "anio BETWEEN 1900 AND 32767");

                            t.HasCheckConstraint("ck_retencion_boleta_porcentaje", "porcentaje BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.AnnualHourlyRate", b =>
                {
                    b.Property<Guid>("ProfessionalInstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_institucion_id");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("HourlyRateClp")
                        .HasColumnType("bigint")
                        .HasColumnName("valor_hora_clp");

                    b.HasKey("ProfessionalInstitutionId", "Year", "Version");

                    b.ToTable("tarifas_hora_anuales_versiones", null, t =>
                        {
                            t.HasCheckConstraint("ck_tarifas_hora_anio", "anio BETWEEN 1900 AND 32767");

                            t.HasCheckConstraint("ck_tarifas_hora_clp_json_exact", "valor_hora_clp <= 9007199254740991");

                            t.HasCheckConstraint("ck_tarifas_hora_valor_no_negativo", "valor_hora_clp >= 0");

                            t.HasCheckConstraint("ck_tarifas_hora_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.HourRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PeriodInstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_institucion_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PeriodInstitutionId", "Order")
                        .IsUnique();

                    b.ToTable("registros_horas", null, t =>
                        {
                            t.HasCheckConstraint("ck_registros_horas_minimo_uno", "horas >= 1");

                            t.HasCheckConstraint("ck_registros_horas_orden", "orden >= 0");

                            t.HasCheckConstraint("ck_registros_horas_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.MonthlyPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AppliedRetentionPercentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("retencion_porcentaje_aplicado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GrossTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("bruto_total_clp");

                    b.Property<short>("Month")
                        .HasColumnType("smallint")
                        .HasColumnName("mes");

                    b.Property<long>("NetTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("liquido_total_clp");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.Property<long>("RetentionTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("retencion_total_clp");

                    b.Property<long>("TotalHours")
                        .HasColumnType("bigint")
                        .HasColumnName("total_horas");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.HasKey("Id");

                    b.HasIndex("Year");

                    b.HasIndex("ProfessionalId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("periodos_mensuales", null, t =>
                        {
                            t.HasCheckConstraint("ck_periodos_mensuales_json_exact", "total_horas <= 9007199254740991 AND bruto_total_clp <= 9007199254740991 AND retencion_total_clp <= 9007199254740991 AND liquido_total_clp <= 9007199254740991");

                            t.HasCheckConstraint("ck_periodos_mensuales_liquido_consistente", "retencion_total_clp <= bruto_total_clp AND liquido_total_clp = bruto_total_clp - retencion_total_clp");

                            t.HasCheckConstraint("ck_periodos_mensuales_mes", "mes BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_periodos_mensuales_retencion_aplicada", "retencion_porcentaje_aplicado BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_periodos_mensuales_totales_no_negativos", "total_horas >= 0 AND bruto_total_clp >= 0 AND retencion_total_clp >= 0 AND liquido_total_clp >= 0");

                            t.HasCheckConstraint("ck_periodos_mensuales_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.PeriodInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GrossTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("bruto_total_clp");

                    b.Property<int>("HourlyRateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("tarifa_hora_version");

                    b.Property<long>("NetTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("liquido_total_clp");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.Property<Guid>("ProfessionalInstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_institucion_id");

                    b.Property<long>("RetentionTotalClp")
                        .HasColumnType("bigint")
                        .HasColumnName("retencion_total_clp");

                    b.Property<long>("TotalHours")
                        .HasColumnType("bigint")
                        .HasColumnName("total_horas");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "ProfessionalInstitutionId")
                        .IsUnique();

                    b.HasIndex("ProfessionalId", "Year");

                    b.HasIndex("ProfessionalInstitutionId", "ProfessionalId");

                    b.HasIndex("PeriodId", "ProfessionalId", "Year");

                    b.HasIndex("ProfessionalInstitutionId", "Year", "HourlyRateVersion");

                    b.ToTable("periodos_instituciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_periodos_instituciones_json_exact", "total_horas <= 9007199254740991 AND bruto_total_clp <= 9007199254740991 AND retencion_total_clp <= 9007199254740991 AND liquido_total_clp <= 9007199254740991");

                            t.HasCheckConstraint("ck_periodos_instituciones_liquido_consistente", "retencion_total_clp <= bruto_total_clp AND liquido_total_clp = bruto_total_clp - retencion_total_clp");

                            t.HasCheckConstraint("ck_periodos_instituciones_orden", "orden >= 0");

                            t.HasCheckConstraint("ck_periodos_instituciones_totales_no_negativos", "total_horas >= 0 AND bruto_total_clp >= 0 AND retencion_total_clp >= 0 AND liquido_total_clp >= 0");

                            t.HasCheckConstraint("ck_periodos_instituciones_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profesionales", null, t =>
                        {
                            t.HasCheckConstraint("ck_profesionales_nombre_not_blank", "length(btrim(nombre)) > 0");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.ProfessionalInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.Property<Guid>("PublicInstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institucion_publica_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PublicInstitutionId");

                    b.HasIndex("ProfessionalId", "Active");

                    b.HasIndex("ProfessionalId", "PublicInstitutionId")
                        .IsUnique();

                    b.ToTable("profesionales_instituciones", (string)null);
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.PublicInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Active", "Name");

                    b.ToTable("instituciones_publicas", null, t =>
                        {
                            t.HasCheckConstraint("ck_instituciones_publicas_nombre_not_blank", "length(btrim(nombre)) > 0");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Data.AuthSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_absoluta_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_inactividad_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RefreshFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_refresh_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_at");

                    b.Property<Guid>("Sid")
                        .HasColumnType("uuid")
                        .HasColumnName("sid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("Sid")
                        .IsUnique();

                    b.HasIndex("UserId", "AbsoluteExpiresAt")
                        .HasFilter("revocada_at IS NULL");

                    b.ToTable("sesiones_auth", null, t =>
                        {
                            t.HasCheckConstraint("ck_sesiones_auth_expiraciones", "expira_inactividad_at <= expira_absoluta_at");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Data.RotatedRefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("RefreshFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_refresh_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset>("RotatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotado_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshFamilyId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("sesiones_refresh_rotados", (string)null);
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_roles_codigo", "codigo IN ('ADMINISTRADOR', 'PROFESIONAL')");
                        });
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cambio_contrasena_requerido");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_access_failed_count", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_usuarios_user_name_not_blank", "length(btrim(user_name)) > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuarios_tokens", (string)null);
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.AnnualHourlyRate", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.ProfessionalInstitution", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.HourRecord", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.PeriodInstitution", null)
                        .WithMany("HourRecords")
                        .HasForeignKey("PeriodInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.MonthlyPeriod", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionIngresosHonorarios.Application.Contracts.AnnualRetentionRate", null)
                        .WithMany()
                        .HasForeignKey("Year")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.PeriodInstitution", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.ProfessionalInstitution", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalInstitutionId", "ProfessionalId")
                        .HasPrincipalKey("Id", "ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.MonthlyPeriod", null)
                        .WithMany("Institutions")
                        .HasForeignKey("PeriodId", "ProfessionalId", "Year")
                        .HasPrincipalKey("Id", "ProfessionalId", "Year")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.AnnualHourlyRate", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalInstitutionId", "Year", "HourlyRateVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.Professional", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.ProfessionalInstitution", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionIngresosHonorarios.Domain.Entities.PublicInstitution", null)
                        .WithMany()
                        .HasForeignKey("PublicInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Data.AuthSessionRecord", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Infrastructure.Data.RotatedRefreshTokenRecord", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Data.AuthSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GestionIngresosHonorarios.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.MonthlyPeriod", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("GestionIngresosHonorarios.Domain.Entities.PeriodInstitution", b =>
                {
                    b.Navigation("HourRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
