CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE instituciones_publicas (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    nombre character varying(200) NOT NULL,
    activa boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_instituciones_publicas" PRIMARY KEY (id),
    CONSTRAINT ck_instituciones_publicas_nombre_not_blank CHECK (length(btrim(nombre)) > 0)
);

CREATE TABLE retencion_boleta_honorarios (
    anio smallint NOT NULL,
    porcentaje numeric(7,4) NOT NULL,
    CONSTRAINT "PK_retencion_boleta_honorarios" PRIMARY KEY (anio),
    CONSTRAINT ck_retencion_boleta_anio CHECK (anio BETWEEN 1900 AND 32767),
    CONSTRAINT ck_retencion_boleta_porcentaje CHECK (porcentaje BETWEEN 0 AND 100)
);

CREATE TABLE roles (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    codigo character varying(50) NOT NULL,
    nombre character varying(100) NOT NULL,
    normalized_name character varying(100) NOT NULL,
    concurrency_stamp text NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (id),
    CONSTRAINT ck_roles_codigo CHECK (codigo IN ('ADMINISTRADOR', 'PROFESIONAL'))
);

CREATE TABLE usuarios (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    activo boolean NOT NULL DEFAULT TRUE,
    cambio_contrasena_requerido boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    user_name character varying(256) NOT NULL,
    normalized_user_name character varying(256) NOT NULL,
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL DEFAULT FALSE,
    password_hash text NOT NULL,
    security_stamp text NOT NULL,
    concurrency_stamp text NOT NULL,
    phone_number character varying(32),
    phone_number_confirmed boolean NOT NULL DEFAULT FALSE,
    two_factor_enabled boolean NOT NULL DEFAULT FALSE,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL DEFAULT TRUE,
    access_failed_count integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_usuarios" PRIMARY KEY (id),
    CONSTRAINT ck_usuarios_access_failed_count CHECK (access_failed_count >= 0),
    CONSTRAINT ck_usuarios_user_name_not_blank CHECK (length(btrim(user_name)) > 0)
);

CREATE TABLE roles_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    rol_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_roles_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_roles_claims_roles_rol_id" FOREIGN KEY (rol_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE profesionales (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    usuario_id uuid NOT NULL,
    nombre character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_profesionales" PRIMARY KEY (id),
    CONSTRAINT ck_profesionales_nombre_not_blank CHECK (length(btrim(nombre)) > 0),
    CONSTRAINT "FK_profesionales_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE RESTRICT
);

CREATE TABLE sesiones_auth (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    usuario_id uuid NOT NULL,
    sid uuid NOT NULL,
    familia_refresh_id uuid NOT NULL,
    refresh_token_hash character varying(128) NOT NULL,
    creada_at timestamp with time zone NOT NULL DEFAULT (now()),
    ultimo_uso_at timestamp with time zone NOT NULL DEFAULT (now()),
    expira_inactividad_at timestamp with time zone NOT NULL,
    expira_absoluta_at timestamp with time zone NOT NULL,
    revocada_at timestamp with time zone,
    CONSTRAINT "PK_sesiones_auth" PRIMARY KEY (id),
    CONSTRAINT ck_sesiones_auth_expiraciones CHECK (expira_inactividad_at <= expira_absoluta_at),
    CONSTRAINT "FK_sesiones_auth_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE RESTRICT
);

CREATE TABLE usuarios_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    usuario_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_usuarios_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_usuarios_claims_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE usuarios_logins (
    login_provider character varying(128) NOT NULL,
    provider_key character varying(128) NOT NULL,
    provider_display_name text,
    usuario_id uuid NOT NULL,
    CONSTRAINT "PK_usuarios_logins" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_usuarios_logins_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE usuarios_roles (
    usuario_id uuid NOT NULL,
    rol_id uuid NOT NULL,
    asignado_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_usuarios_roles" PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT "FK_usuarios_roles_roles_rol_id" FOREIGN KEY (rol_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT "FK_usuarios_roles_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE usuarios_tokens (
    usuario_id uuid NOT NULL,
    login_provider character varying(128) NOT NULL,
    nombre character varying(128) NOT NULL,
    valor text,
    CONSTRAINT "PK_usuarios_tokens" PRIMARY KEY (usuario_id, login_provider, nombre),
    CONSTRAINT "FK_usuarios_tokens_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE periodos_mensuales (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    profesional_id uuid NOT NULL,
    anio smallint NOT NULL,
    mes smallint NOT NULL,
    retencion_porcentaje_aplicado numeric(7,4) NOT NULL,
    total_horas bigint NOT NULL,
    bruto_total_clp bigint NOT NULL,
    retencion_total_clp bigint NOT NULL,
    liquido_total_clp bigint NOT NULL,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_periodos_mensuales" PRIMARY KEY (id),
    CONSTRAINT "AK_periodos_mensuales_id_profesional_id_anio" UNIQUE (id, profesional_id, anio),
    CONSTRAINT ck_periodos_mensuales_json_exact CHECK (total_horas <= 9007199254740991 AND bruto_total_clp <= 9007199254740991 AND retencion_total_clp <= 9007199254740991 AND liquido_total_clp <= 9007199254740991),
    CONSTRAINT ck_periodos_mensuales_liquido_consistente CHECK (retencion_total_clp <= bruto_total_clp AND liquido_total_clp = bruto_total_clp - retencion_total_clp),
    CONSTRAINT ck_periodos_mensuales_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_periodos_mensuales_retencion_aplicada CHECK (retencion_porcentaje_aplicado BETWEEN 0 AND 100),
    CONSTRAINT ck_periodos_mensuales_totales_no_negativos CHECK (total_horas >= 0 AND bruto_total_clp >= 0 AND retencion_total_clp >= 0 AND liquido_total_clp >= 0),
    CONSTRAINT ck_periodos_mensuales_version CHECK (version >= 1),
    CONSTRAINT "FK_periodos_mensuales_profesionales_profesional_id" FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_periodos_mensuales_retencion_boleta_honorarios_anio" FOREIGN KEY (anio) REFERENCES retencion_boleta_honorarios (anio) ON DELETE RESTRICT
);

CREATE TABLE profesionales_instituciones (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    profesional_id uuid NOT NULL,
    institucion_publica_id uuid NOT NULL,
    activa boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_profesionales_instituciones" PRIMARY KEY (id),
    CONSTRAINT "AK_profesionales_instituciones_id_profesional_id" UNIQUE (id, profesional_id),
    CONSTRAINT "FK_profesionales_instituciones_instituciones_publicas_instituc~" FOREIGN KEY (institucion_publica_id) REFERENCES instituciones_publicas (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_profesionales_instituciones_profesionales_profesional_id" FOREIGN KEY (profesional_id) REFERENCES profesionales (id) ON DELETE RESTRICT
);

CREATE TABLE sesiones_refresh_rotados (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    sesion_id uuid NOT NULL,
    familia_refresh_id uuid NOT NULL,
    refresh_token_hash character varying(128) NOT NULL,
    rotado_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_sesiones_refresh_rotados" PRIMARY KEY (id),
    CONSTRAINT "FK_sesiones_refresh_rotados_sesiones_auth_sesion_id" FOREIGN KEY (sesion_id) REFERENCES sesiones_auth (id) ON DELETE RESTRICT
);

CREATE TABLE tarifas_hora_anuales_versiones (
    profesional_institucion_id uuid NOT NULL,
    anio smallint NOT NULL,
    version integer NOT NULL,
    valor_hora_clp bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_tarifas_hora_anuales_versiones" PRIMARY KEY (profesional_institucion_id, anio, version),
    CONSTRAINT ck_tarifas_hora_anio CHECK (anio BETWEEN 1900 AND 32767),
    CONSTRAINT ck_tarifas_hora_clp_json_exact CHECK (valor_hora_clp <= 9007199254740991),
    CONSTRAINT ck_tarifas_hora_valor_no_negativo CHECK (valor_hora_clp >= 0),
    CONSTRAINT ck_tarifas_hora_version CHECK (version >= 1),
    CONSTRAINT "FK_tarifas_hora_anuales_versiones_profesionales_instituciones_~" FOREIGN KEY (profesional_institucion_id) REFERENCES profesionales_instituciones (id) ON DELETE RESTRICT
);

CREATE TABLE periodos_instituciones (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    periodo_id uuid NOT NULL,
    profesional_id uuid NOT NULL,
    anio smallint NOT NULL,
    profesional_institucion_id uuid NOT NULL,
    tarifa_hora_version integer NOT NULL,
    total_horas bigint NOT NULL,
    bruto_total_clp bigint NOT NULL,
    retencion_total_clp bigint NOT NULL,
    liquido_total_clp bigint NOT NULL,
    orden integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_periodos_instituciones" PRIMARY KEY (id),
    CONSTRAINT ck_periodos_instituciones_json_exact CHECK (total_horas <= 9007199254740991 AND bruto_total_clp <= 9007199254740991 AND retencion_total_clp <= 9007199254740991 AND liquido_total_clp <= 9007199254740991),
    CONSTRAINT ck_periodos_instituciones_liquido_consistente CHECK (retencion_total_clp <= bruto_total_clp AND liquido_total_clp = bruto_total_clp - retencion_total_clp),
    CONSTRAINT ck_periodos_instituciones_orden CHECK (orden >= 0),
    CONSTRAINT ck_periodos_instituciones_totales_no_negativos CHECK (total_horas >= 0 AND bruto_total_clp >= 0 AND retencion_total_clp >= 0 AND liquido_total_clp >= 0),
    CONSTRAINT ck_periodos_instituciones_version CHECK (version >= 1),
    CONSTRAINT "FK_periodos_instituciones_periodos_mensuales_periodo_id_profes~" FOREIGN KEY (periodo_id, profesional_id, anio) REFERENCES periodos_mensuales (id, profesional_id, anio) ON DELETE RESTRICT,
    CONSTRAINT "FK_periodos_instituciones_profesionales_instituciones_profesio~" FOREIGN KEY (profesional_institucion_id, profesional_id) REFERENCES profesionales_instituciones (id, profesional_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_periodos_instituciones_tarifas_hora_anuales_versiones_profe~" FOREIGN KEY (profesional_institucion_id, anio, tarifa_hora_version) REFERENCES tarifas_hora_anuales_versiones (profesional_institucion_id, anio, version) ON DELETE RESTRICT
);

CREATE TABLE registros_horas (
    id uuid NOT NULL DEFAULT (gen_random_uuid()),
    periodo_institucion_id uuid NOT NULL,
    horas integer NOT NULL,
    orden integer NOT NULL,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_registros_horas" PRIMARY KEY (id),
    CONSTRAINT ck_registros_horas_minimo_uno CHECK (horas >= 1),
    CONSTRAINT ck_registros_horas_orden CHECK (orden >= 0),
    CONSTRAINT ck_registros_horas_version CHECK (version >= 1),
    CONSTRAINT "FK_registros_horas_periodos_instituciones_periodo_institucion_~" FOREIGN KEY (periodo_institucion_id) REFERENCES periodos_instituciones (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_instituciones_publicas_activa_nombre" ON instituciones_publicas (activa, nombre);

CREATE INDEX "IX_periodos_instituciones_periodo_id_profesional_id_anio" ON periodos_instituciones (periodo_id, profesional_id, anio);

CREATE UNIQUE INDEX "IX_periodos_instituciones_periodo_id_profesional_institucion_id" ON periodos_instituciones (periodo_id, profesional_institucion_id);

CREATE INDEX "IX_periodos_instituciones_profesional_id_anio" ON periodos_instituciones (profesional_id, anio);

CREATE INDEX "IX_periodos_instituciones_profesional_institucion_id_anio_tari~" ON periodos_instituciones (profesional_institucion_id, anio, tarifa_hora_version);

CREATE INDEX "IX_periodos_instituciones_profesional_institucion_id_profesion~" ON periodos_instituciones (profesional_institucion_id, profesional_id);

CREATE INDEX "IX_periodos_mensuales_anio" ON periodos_mensuales (anio);

CREATE UNIQUE INDEX "IX_periodos_mensuales_profesional_id_anio_mes" ON periodos_mensuales (profesional_id, anio, mes);

CREATE UNIQUE INDEX "IX_profesionales_usuario_id" ON profesionales (usuario_id);

CREATE INDEX "IX_profesionales_instituciones_institucion_publica_id" ON profesionales_instituciones (institucion_publica_id);

CREATE INDEX "IX_profesionales_instituciones_profesional_id_activa" ON profesionales_instituciones (profesional_id, activa);

CREATE UNIQUE INDEX "IX_profesionales_instituciones_profesional_id_institucion_publ~" ON profesionales_instituciones (profesional_id, institucion_publica_id);

CREATE UNIQUE INDEX "IX_registros_horas_periodo_institucion_id_orden" ON registros_horas (periodo_institucion_id, orden);

CREATE UNIQUE INDEX "IX_roles_codigo" ON roles (codigo);

CREATE UNIQUE INDEX "RoleNameIndex" ON roles (normalized_name);

CREATE INDEX "IX_roles_claims_rol_id" ON roles_claims (rol_id);

CREATE UNIQUE INDEX "IX_sesiones_auth_refresh_token_hash" ON sesiones_auth (refresh_token_hash);

CREATE UNIQUE INDEX "IX_sesiones_auth_sid" ON sesiones_auth (sid);

CREATE INDEX "IX_sesiones_auth_usuario_id_expira_absoluta_at" ON sesiones_auth (usuario_id, expira_absoluta_at) WHERE revocada_at IS NULL;

CREATE INDEX "IX_sesiones_refresh_rotados_familia_refresh_id" ON sesiones_refresh_rotados (familia_refresh_id);

CREATE UNIQUE INDEX "IX_sesiones_refresh_rotados_refresh_token_hash" ON sesiones_refresh_rotados (refresh_token_hash);

CREATE INDEX "IX_sesiones_refresh_rotados_sesion_id" ON sesiones_refresh_rotados (sesion_id);

CREATE UNIQUE INDEX "EmailIndex" ON usuarios (normalized_email) WHERE normalized_email IS NOT NULL;

CREATE UNIQUE INDEX "UserNameIndex" ON usuarios (normalized_user_name);

CREATE INDEX "IX_usuarios_claims_usuario_id" ON usuarios_claims (usuario_id);

CREATE INDEX "IX_usuarios_logins_usuario_id" ON usuarios_logins (usuario_id);

CREATE INDEX "IX_usuarios_roles_rol_id" ON usuarios_roles (rol_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005173446_InitialCreate', '10.0.12');

COMMIT;

